baseURL = 'https://ievangelist.github.io/azure-cosmos-dotnet-repository/'
languageCode = 'en-us'
title = 'Azure Cosmos .NET Repository - Docs'

theme = "hugo-theme-learn"

[params]
    themeVariant = "blue"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
